### PR TITLE
Added custom browserContext for each session

### LINKED ISSUE #110: Cannot open multiple {headless: false} browsers on macos arm
Minimal reproducible example:
main.ts:
```ts
import { launch } from "jsr:@astral/astral";

function randomIntFromInterval(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

async function performTask() {
  // Launch the browser
  const browser = await launch({ headless : false });
}


async function runMultipleBrowsers() {
    for (let i = 0; i < 2; i++) {
      await new Promise((resolve) => setTimeout(resolve, randomIntFromInterval(0, 1000)));
      performTask();
    }
}
runMultipleBrowsers();
```
```bash
deno run --allow-net --allow-env --allow-read --allow-write --allow-run main.ts
```
Macos version: 14.7 (23H124) (Sonoma)

Error:
```
Process exited with code 0
error: Uncaught (in promise) Error: Your binary refused to boot
    throw new Error("Your binary refused to boot");
          ^
    at runCommand (https://jsr.io/@astral/astral/0.4.8/src/browser.ts:65:11)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async launch (https://jsr.io/@astral/astral/0.4.8/src/browser.ts:289:33)
    at async performTask (file:///Users/tom/programming/tade/bot/minimalExample.ts:9:19)
Process exited with code 1
```

It works completely fine when I launch only one browser instance or if I launch with {headless:true}.

The problematic line:

[https://github.com/lino-levan/astral/blob/7ce5b21da5bd91b03df2e80c9ab3998cfeb123ed/src/browser.ts#L65](https://github.com/lino-levan/astral/blob/7ce5b21da5bd91b03df2e80c9ab3998cfeb123ed/src/browser.ts#L65)

### PR DESCRIPTION
**Pull request by tpkowastaken**
Close #110

### CODE REVIEW

**Comment by lino-levan** [comment]
Does this fix it? I'm curious on why this would fix it when our `--user-data-dir` code like 5 lines down would not.

**Comment by tpkowastaken** [comment]
That's weird. It works just this way. Also when I'm looking into the old 0.3.5 version it looks similar to what I'm suggesting.

https://deno.land/x/astral@0.3.5/src/browser.ts?source#L242

**Comment by tpkowastaken** [comment]
Nevermind. What a rookie mistake I oversaw. We're applying the args parameter to the binargs before adding the --user-data-dir parameter. 😄 I will edit that right now.

**Comment by lino-levan** [comment]
> We're applying the args parameter to the binargs before adding the --user-data-dir parameter. 😄 I will edit that right now.

Ahhh, right. Thanks for catching this.

**Pull request merged**
